spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://11.0.0.184:10080/spring-cloud-study/remote-config.git
          search-paths: repo
          username: wenhao
          password: 123456

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/